
spring:
  application:
    name: alias-shop-auth-server
#  datasource: #druid数据源配置
#    druid:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc://mysql://120.77.205.9:3306/alias_shop?useUnicode=true&characterEncoding=UTF8
#      username: alias
#      password: chen8999958...
#      #连接池参数，初始数、最大数、最小数、获取连接等待超时时间（毫秒）
#      initial-size: 5
#      max-active: 20
#      min-idle: 5
#      max-wait: 60000

  datasource:
    name: test
    url: jdbc:mysql://120.77.205.9:3306/alias_shop?useUnicode=true&characterEncoding=UTF8
    username: alias
    password: chen8999958...
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
  cloud:
    config:
      uri: https://github.com/ChenShnegLi/alias-shop-config-repo.git
      label: master
      profile: dev

#  redis:
#    password: chen8999958...
#    host: 120.77.205.9
#    url: 120.77.205.9
#    port: 6379
#    #timeout:
#    jedis:
#     pool:
#       max-active:
#         min-idle: 0
#         max-idle: 0
#         max-wait: -1
eureka:
  instance:
    non-secure-port: ${server.port:8889}
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:${eureka.port:8761}/eureka/

mybatis:
    basepackage: cn.alias.shop.auth.serviceDal.mapper
    mapper-locations: classpath:mapper/*.xml
   # xmlLocation: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
        loggerLevel: basic
# To disable Hystrix in Feign
  hystrix:
    enabled: true